{{- if .Values.guestbook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guestbook-go.serviceAccountName" . }}
  labels:
    {{- include "guestbook-go.labels" . | nindent 4 }}
{{- end }}