apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-go.fullname" . }}
  labels:
    {{- include "guestbook-go.labels" . | nindent 4 }}
    component: guestbook
spec:
  type: {{ .Values.guestbook.service.type }}
  ports:
    - port: {{ .Values.guestbook.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "guestbook-go.selectorLabels" . | nindent 4 }}
    component: guestbook
